version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /system/db:/var/lib/postgresql/data
      - ./system/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  service:
    container_name: service
    build: .
    depends_on:
      - db
    ports:
      - "7001:7001"
    links:
      - db
    command: go run cmd/main.go
volumes:
  db:
    driver: local